------------------------------------------------------Wprowadzenie danych lekarzy ------------------------------------------------------

INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Alexander','Nieves',1,'Cardiologist','Cardiology');	
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Elijah','Macdonald',2,'Immunologist','Children ward');  
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Wallace','Parker',3,'Psychiatrist','Neurology');
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Odessa','Campbell',4,'Surgeon','Children ward');
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Quentin','Walsh',5,'Ortopaedist','Physiotherapy');
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Colin','Mclaughlin',6,'Psychologist','Children ward');
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Gareth','Madden',7,'Cardiologist','Cardiology');
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Cathleen','Scott',8,'Neurologist','Neurology');
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Kalia','Aguilar',9,'Therapist','Cardiology');       
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Neve','Kline',10,'Therapist','Anesthesiology');
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Merritt','Leon',11,'Psychologist','Seniors ward');
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Hedda','Valdez',12,'Cardiologist','Cardiology');		
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Quinn','Lewis',13,'Anesthesiologist','Anesthesiology');
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Petra','Moss',14,'Anesthesiologist','Anesthesiology');
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Nathaniel','Mckenzie',15,'Therapist','Cardiology');	
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Pamela','Heath',16,'Cardiologist','Children ward');
INSERT INTO DOCTORS (FIRST_NAME,SURNAME,DOCTOR_ID,SPECJALIZATION,WARD_NAME) VALUES ('Molly','Carrillo',17,'Ortopaedist','Children ward');



--------------------------------------------------Wprowadzenie danych sal oddziałowych----------------------------------------------------

INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (1,7,'Y',5,'Cardiology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (2,9,'N',1,'Physiotherapy');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (3,7,'Y',2,'Surgery');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (4,6,'Y',3,'Neurology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (5,6,'Y',4,'Neurology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (6,9,'Y',5,'Seniors ward');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (7,7,'N',1,'Physiotherapy');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (8,8,'Y',1,'Surgery');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (9,9,'Y',5,'Children ward');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (10,9,'Y',1,'Seniors ward');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (11,6,'N',1,'Neurology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (12,9,'Y',6,'Anesthesiology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (13,5,'N',4,'Seniors ward');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (14,10,'N',2,'Physiotherapy');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (15,6,'Y',3,'Sugery');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (16,6,'N',1,'Neurology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (17,10,'Y',4,'Surgery');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (18,5,'N',3,'Physiotherapy');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (19,9,'Y',6,'Children ward');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (20,10,'N',1,'Physiotherapy');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (21,10,'Y',2,'Cardiology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (22,7,'Y',6,'Seniors ward');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (23,9,'N',5,'Surgery');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (24,9,'Y',3,'Seniors ward');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (25,5,'Y',3,'Surgery');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (26,9,'N',4,'Physiotherapy');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (27,6,'N',1,'Neurology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (28,8,'N',5,'Children ward');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (29,5,'Y',5,'Cardiology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (30,6,'N',2,'Physiotherapy');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (31,6,'N',4,'Neurology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (32,5,'Y',4,'Cardiology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (33,8,'N',4,'Children ward');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (34,6,'Y',6,'Anesthesiology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (35,10,'Y',4,'Neurology');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (36,5,'N',1,'Physiotherapy');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (37,7,'Y',3,'Surgery');
INSERT INTO ROOMS (ROOM_ID,BED_COUNT,WC,FLOOR,WARD_NAME) VALUES (38,9,'Y',3,'Neurology');



-------------------------------------------------------------Wprowadzenie danych pacjentów----------------------------------------------------

INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Alice','Hatfield',1,'97/02/02','F','869348478',9);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Tashya','Skinner',2,'98/03/06','F','332414882',17);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Zeph','Fernandez',3,'86/12/04','M','457348533',15);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Lars','Lancaster',4,'86/05/10','M','464542675',5);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Lester','Henderson',5,'96/12/22','F','467393215',17);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Elijah','Rodgers',6,'94/02/15','M','939511913',14);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Paul','Booker',7,'78/09/11','M','996935491',14);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Wesley','Lee',8,'77/04/01','M','736114435',14);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Aidan','Macias',9,'99/03/22','M','143263345',1);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Ella','Estrada',10,'61/01/11','F','617243725',5);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Kareem','Callahan',11,'77/06/13','F','187542237',10);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Brianna','Hahn',12,'99/12/19','F','469458647',6);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Zeph','Cole',13,'92/02/28','M','335176484',8);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Noah','Wynn',14,'90/08/18','M','948612742',17);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Kirsten','Wilkins',15,'94/07/10','F','558584474',11);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Vivian','Montoya',16,'71/04/08','F','911886958',3);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Mufutau','Shannon',17,'71/06/14','M','483248826',5);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Wallace','Hutchinson',18,'68/07/14','M','296378324',5);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Yuli','Russo',19,'79/12/15','F','296369911',3);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Stone','Mccormick',20,'81/02/23','M','117915812',4);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Willa','Garrett',21,'63/06/05','F','354795446',6);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Lani','Vinson',22,'80/05/19','F','375845698',15);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Kaden','Hoffman',23,'90/06/27','F','319761816',4);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Camille','Waters',24,'72/05/17','F','732328548',16);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Sebastian','Burt',25,'64/04/10','M','163965555',3);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Amaya','Mcgowan',26,'98/06/21','F','776757623',10);
INSERT INTO PATIENTS (FIRST_NAME,SURNAME,PATIENT_ID,BIRTH_DATE,SEX,PHONE,DOCTOR_ID) VALUES ('Ciara','Morin',27,'75/03/28','F','674942389',14);


----------- Przypisanie sal dla części pacjentów -------------
UPDATE Patients 
SET room_id = 29
WHERE doctor_id = 1 
OR doctor_id = 7
OR doctor_id = 9
OR doctor_id = 12
OR doctor_id = 15;

UPDATE Patients 
SET room_id = 9
WHERE doctor_id = 2 
OR doctor_id = 6
OR doctor_id = 16
OR doctor_id = 17;

UPDATE Patients 
SET room_id = 5
WHERE doctor_id = 3 
OR doctor_id = 8;

UPDATE Patients 
SET room_id = 34
WHERE doctor_id = 10
OR doctor_id = 13
OR doctor_id = 14;